# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3814e16b4294c883c028e5eaa2040ac52ba781dfcffc0465845bd5a4bf1c6ddbafa26fd3976fd7fc466f31145cbb307c667cc7d2cd34f0c7fd810bc127ef31a7

test:
  secret_key_base: 86f6954d6e555dcaac10756451d7710e30a4012eac62779723c2e32bfbd8f8d42c1fa6ca0dcf3e61c0346287d96a265507bec644b81b0edfd2bc13365135bc95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
